// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pjntzmwoxccjqmkscpqm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBqbnR6bXdveGNjanFta3NjcHFtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5NjI1NTIsImV4cCI6MjA2NTUzODU1Mn0.uDmhc7VWot8cbV8L8FFJML_PnhCQAvvVEg9Pc8AJy0M";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);